/*
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 * Copyright (C) 2014 Jakub Kicinski <kubakici@wp.pl>
 */

/* Bigger tool which uses libpcap to read statistics generated by NetFPGA
 * from file or directly from the capturing interface and does calculations.
 */

#include "mgr_interp.h"

#include <dirent.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#include <ccan/opt/opt.h>
#include <ccan/tal/tal.h>

struct cmdline_args args = {
	.res_dir = "./",
};

static struct opt_table opts[] = {
	OPT_WITH_ARG("-p|--pfx <prefix>", opt_set_charp, NULL,
		     &args.res_pfx, "read files from result dir with names <prefix>*"),
	OPT_WITH_ARG("-d|--res-dir <path>", opt_set_charp, NULL,
		     &args.res_dir, "look for result files in <path>, default ./"),
	OPT_WITH_ARG("-i|--ifg <clks>", opt_set_intval, NULL,
		     &args.ifg, "expected inter frame gap"),
	OPT_WITH_ARG("-D|--distribution <dir>", opt_set_charp, NULL,
		     &args.distr, "dump distributions to given directory"),
	OPT_WITH_ARG("-H|--heatmap <dir>", opt_set_charp, NULL,
		     &args.hm, "dump heatmaps to given directory"),
	OPT_WITH_ARG("-n|--aggregate <n>", opt_set_intval, NULL,
		     &args.aggr, "aggregation for simple statistics (bucket size)"),
	OPT_WITHOUT_ARG("-q|--quiet", opt_set_bool,
			&args.quiet, "suppress text output"),
	OPT_ENDTABLE
};

typedef int (*delay2file_fn)(struct delay *d, FILE *f);

#define aggr(_t_) ((d->t[_t_].samples[i] - d->min_sample) / args.aggr)
#define deaggr(_i_) (d->min_sample + _i_ * args.aggr)
static int make_distr(struct delay *d, FILE *f)
{
	u32 i, t;
	u32 *distr_table[3];
	u32 table_size = 1 + (d->max_sample - d->min_sample) / args.aggr;

	for (t = 0; t < 3; t++) {
		distr_table[t] =
			calloc(table_size, sizeof(u32));

		for (i = 0; i < d->n_samples; i++)
			distr_table[t][aggr(t)]++;
	}

	for (i = 0; i < table_size; i++)
		if (distr_table[0][i] ||
		    distr_table[1][i] ||
		    distr_table[2][i])
			fprintf(f, "%d %u %u %u\n", deaggr(i)*8,
				distr_table[0][i],
				distr_table[1][i],
				distr_table[2][i]);

	for (t = 0; t < 3; t++)
		free(distr_table[t]);

	return 0;
}

static int make_hm(struct delay *d, FILE *f)
{
	u32 i, j;
	u32 **hm_table;
	u32 dim = 1 + (d->max_sample - d->min_sample) / args.aggr;

	hm_table = calloc(dim, sizeof(*hm_table));
	for (i = 0; i < dim; i++)
		hm_table[i] = calloc(dim, sizeof(**hm_table));

	for (i = 0; i < d->n_samples; i++)
		hm_table[aggr(0)][aggr(1)]++;

	for (i = 0; i < dim; i++) {
		for (j = 0; j < dim; j++)
			fprintf(f, "%d ", hm_table[i][j]);
		fputc('\n', f);
	}

	for (i = 0; i < dim; i++)
		free(hm_table[i]);
	free(hm_table);

	return 0;
}
#undef aggr
#undef deggr

static inline int make_delay_file(struct delay *d, delay2file_fn make_single)
{
	int ret;
	FILE *f;

	f = fopen(d->fname, "w");
	if (!f)
		return perr_ret("Opening distr file to write failed");

	ret = make_single(d, f);

	fclose(f);

	return ret;
}

static int make_per_delay(const char *dir, struct delay_bank *db,
			  delay2file_fn make_single)
{
	int i, res;
	char *cwd;

	res = mkdir(dir, 0777);
	if (res && errno != EEXIST)
		return perr_ret("Could not create distribution directory\n");

	cwd = get_current_dir_name();
	if (!cwd)
		return perr_ret("Could not get current dir");
	if (chdir(dir))
		return perr_ret("Could not go to the result dir");

	for (i = 0; i < db->n; i++)
		make_delay_file(db->bank[i], make_single);

	chdir(cwd);
	free(cwd);

	return 0;
}

static struct delay_bank *open_many(const char *dir, const char *pfx)
{
	DIR *d;
	struct dirent *ent;
	int pfx_len = strlen(pfx);
	char *cwd;
	struct delay_bank *rb;

	cwd = get_current_dir_name();
	if (!cwd)
		return perr_nret("Could not get current dir");
	if (chdir(dir))
		return perr_nret("Could not go to the result dir");

	d = opendir(".");
	if (!d)
		return perr_nret("Could not open the result dir");

	rb = talz(NULL, struct delay_bank);

	while ((ent = readdir(d))) {
		if (strncmp(ent->d_name, pfx, pfx_len))
			continue;

		if (rb->bank)
			tal_resize(&rb->bank, ++rb->n);
		else
			rb->bank = tal_arr(rb, struct delay *, ++rb->n);

		rb->bank[rb->n - 1] = read_delay(ent->d_name);
		if (!rb->bank[rb->n - 1]) {
			tal_free(rb);
			rb = NULL;
			break;
		}
		if (!rb->min_samples ||
		    rb->min_samples > rb->bank[rb->n - 1]->n_samples)
			rb->min_samples = rb->bank[rb->n - 1]->n_samples;
		tal_steal(rb->bank, rb->bank[rb->n - 1]);
	}
	msg("Done reading, every run has at least %u samples\n",
	    rb->min_samples);

	closedir(d);

	chdir(cwd);
	free(cwd);

	return rb;
}

int main(int argc, char **argv)
{
	struct delay_bank *db;

	opt_register_table(opts, NULL);

	if (!opt_parse(&argc, argv, opt_log_stderr))
		return 1;

	opt_free_table();

	if (!args.res_pfx)
		return err_ret("Please specify result file name prefix\n");

	db = open_many(args.res_dir, args.res_pfx);
	if (!db)
		return 1;

	if (args.distr)
		make_per_delay(args.distr, db, make_distr);
	if (args.hm)
		make_per_delay(args.hm, db, make_hm);

	tal_free(db);

	tal_cleanup();

	return 0;
}
