/*
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 * Copyright (C) 2014 Jakub Kicinski <kubakici@wp.pl>
 */

/* Bigger tool which uses libpcap to read statistics generated by NetFPGA
 * from file or directly from the capturing interface and does calculations.
 */

#include "mgr_interp.h"

#include <dirent.h>
#include <string.h>
#include <sys/types.h>
#include <unistd.h>

#include <ccan/opt/opt.h>
#include <ccan/tal/tal.h>

struct cmdline_args args = {
	.res_dir = "./",
};

static struct opt_table opts[] = {
	OPT_WITH_ARG("-p|--pfx <prefix>", opt_set_charp, NULL,
		     &args.res_pfx, "read files from result dir with names <prefix>*"),
	OPT_WITH_ARG("-d|--res-dir <path>", opt_set_charp, NULL,
		     &args.res_dir, "look for result files in <path>, default ./"),
	OPT_WITH_ARG("-i|--ifg <clks>", opt_set_intval, NULL,
		     &args.ifg, "expected inter frame gap"),
	OPT_WITH_ARG("-D|--distribution <dir>", opt_set_charp, NULL,
		     &args.distr, "dump distributions to given directory"),
	OPT_WITH_ARG("-H|--heatmap <dir>", opt_set_charp, NULL,
		     &args.hm, "dump heatmaps to given directory"),
	OPT_WITH_ARG("-n|--aggregate <n>", opt_set_intval, NULL,
		     &args.aggr, "aggregation for simple statistics (bucket size)"),
	OPT_WITHOUT_ARG("-q|--quiet", opt_set_bool,
			&args.quiet, "suppress text output"),
	OPT_ENDTABLE
};

struct delay_bank *open_many(const char *dir, const char *pfx)
{
	DIR *d;
	struct dirent *ent;
	int pfx_len = strlen(pfx);
	char *cwd;
	int n_res = 0;
	struct delay_bank *rb;

	cwd = get_current_dir_name();
	if (!cwd)
		return perr_nret("Could not get current dir");
	if (chdir(dir))
		return perr_nret("Could not go to the result dir");

	d = opendir(".");
	if (!d)
		return perr_nret("Could not open the result dir");

	rb = talz(NULL, struct delay_bank);

	while ((ent = readdir(d))) {
		if (strncmp(ent->d_name, pfx, pfx_len))
			continue;

		if (rb->bank)
			tal_resize(&rb->bank, ++n_res);
		else
			rb->bank = tal_arr(rb, struct delay *, ++n_res);

		rb->bank[n_res - 1] = read_delay(ent->d_name);
		if (!rb->bank[n_res - 1]) {
			tal_free(rb);
			rb = NULL;
			break;
		}
		tal_steal(rb->bank, rb->bank[n_res - 1]);
	}

	closedir(d);

	chdir(cwd);
	free(cwd);

	return rb;
}

int main(int argc, char **argv)
{
	struct delay_bank *db;

	opt_register_table(opts, NULL);

	if (!opt_parse(&argc, argv, opt_log_stderr))
		return 1;

	opt_free_table();

	if (!args.res_pfx)
		return err_ret("Please specify result file name prefix\n");

	db = open_many(args.res_dir, args.res_pfx);
	if (!db)
		return 1;

	tal_free(db);

	tal_cleanup();

	return 0;
}
